apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: victoromuyadocker/udagram-reverseproxy:v1
        ports:
        - containerPort: 80
        resources: 
          limits:
            cpu: 500m
          requests:
            cpu: 200m